/**
 * File: components/forms/CountrySelectField.tsx
 * Purpose: Country dropdown with search, flags, and full RHF (react-hook-form) integration.
 * Exports: <CountrySelect /> (internal control) and <CountrySelectField /> (RHF wrapper)
 *
 * Key ideas:
 * - Uses `react-select-country-list` for ISO country metadata.
 * - Displays flags using Unicode regional indicators.
 * - Implements a searchable popover using shadcn/ui Command components.
 * - <CountrySelectField /> provides validation, labels, and form error rendering.
 *
 * @remarks
 * - Client-only component: relies on DOM APIs and shadcn popovers → `"use client"`.
 * - `CountrySelect` is intentionally **controlled** via `value` and `onChange`; the form wiring
 *   (validation, errors) lives in the `CountrySelectField` wrapper using react-hook-form.
 * - Flags are derived via Unicode code points (127397 offset), avoiding image assets.
 * - Designed primarily for onboarding/signup flows requiring country selection.
 */

"use client";

import { useState } from "react";
import { Control, Controller, FieldError } from "react-hook-form";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Check, ChevronsUpDown } from "lucide-react";
import { cn } from "@/lib/utils";
import countryList from "react-select-country-list";

type CountrySelectProps = {
  name: string;
  label: string;
  control: Control<any>;
  error?: FieldError;
  required?: boolean;
};

/**
 * CountrySelect
 * @summary Searchable country picker with ISO flags rendered as emojis.
 * @param value - The current selected country code (ISO 3166-1 alpha-2). If falsy, a placeholder is shown.
 * @param onChange - Callback invoked with the selected ISO code.
 *
 * @remarks
 * - Uses `react-select-country-list` to retrieve the full list of countries.
 * - Flags are generated by converting ISO characters into regional indicator symbols.
 * - Popover closes automatically after a selection.
 * - Visuals follow dark theme classes via shadcn/ui.
 */
const CountrySelect = ({
  value,
  onChange,
}: {
  value: string;
  onChange: (value: string) => void;
}) => {
  const [open, setOpen] = useState(false);

  const countries = countryList().getData();

  // Convert ISO code → Unicode flag emoji
  const getFlagEmoji = (countryCode: string) => {
    const codePoints = countryCode
      .toUpperCase()
      .split("")
      .map((char) => 127397 + char.charCodeAt(0));
    return String.fromCodePoint(...codePoints);
  };

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="country-select-trigger"
        >
          {value ? (
            <span className="flex items-center gap-2">
              <span>{getFlagEmoji(value)}</span>
              <span>{countries.find((c) => c.value === value)?.label}</span>
            </span>
          ) : (
            "Select your country..."
          )}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent
        className="w-full p-0 bg-gray-800 border-gray-600"
        align="start"
      >
        <Command className="bg-gray-800 border-gray-600">
          <CommandInput
            placeholder="Search countries..."
            className="country-select-input"
          />
          <CommandEmpty className="country-select-empty">
            No country found.
          </CommandEmpty>
          <CommandList className="max-h-60 bg-gray-800 scrollbar-hide-default">
            <CommandGroup className="bg-gray-800">
              {countries.map((country) => (
                <CommandItem
                  key={country.value}
                  value={`${country.label} ${country.value}`}
                  onSelect={() => {
                    onChange(country.value);
                    setOpen(false);
                  }}
                  className="country-select-item"
                >
                  <Check
                    className={cn(
                      "mr-2 h-4 w-4 text-yellow-500",
                      value === country.value ? "opacity-100" : "opacity-0"
                    )}
                  />
                  <span className="flex items-center gap-2">
                    <span>{getFlagEmoji(country.value)}</span>
                    <span>{country.label}</span>
                  </span>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};

/**
 * CountrySelectField
 * @summary Form-ready wrapper around <CountrySelect /> using react-hook-form.
 * @param props.name - Field name in the form schema.
 * @param props.label - Visible label above the field.
 * @param props.control - React Hook Form control instance.
 * @param props.error - Optional validation error to display under field.
 * @param props.required - Whether selection is required.
 *
 * @remarks
 * - Enforces reactive validation using RHF's `Controller`.
 * - Adds helper text explaining personalization benefits.
 * - Designed for sign-up forms and onboarding flows.
 */
export const CountrySelectField = ({
  name,
  label,
  control,
  error,
  required = false,
}: CountrySelectProps) => {
  return (
    <div className="space-y-2">
      <Label htmlFor={name} className="form-label">
        {label}
      </Label>
      <Controller
        name={name}
        control={control}
        rules={{
          required: required ? `Please select ${label.toLowerCase()}` : false,
        }}
        render={({ field }) => (
          <CountrySelect value={field.value} onChange={field.onChange} />
        )}
      />
      {error && <p className="text-sm text-red-500">{error.message}</p>}
      <p className="text-xs text-gray-500">
        Helps us show market data and news relevant to you.
      </p>
    </div>
  );
};
